config/routes.rb
Rails.application.routes.draw do
  resources :tasks_lists

  root 'tasks_lists#index'

end

app/models/tasks_list.rb
class TasksList < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_lists_controller.rb
class TasksListsController < ApplicationController
  before_action :set_tasks_list, only: [:show, :edit, :update, :destroy]

  # GET /tasks_lists
  # GET /tasks_lists.json
  def index
    @tasks_lists = TasksList.all
  end

  # GET /tasks_lists/1
  # GET /tasks_lists/1.json
  def show
  end

  # GET /tasks_lists/new
  def new
    @tasks_list = TasksList.new
  end

  # GET /tasks_lists/1/edit
  def edit
  end

  # POST /tasks_lists
  # POST /tasks_lists.json
  def create
    @tasks_list = TasksList.new(tasks_list_params)

    respond_to do |format|
      if @tasks_list.save
        format.html { redirect_to @tasks_list, notice: 'Tasks list was successfully created.' }
        format.json { render :show, status: :created, location: @tasks_list }
      else
        format.html { render :new }
        format.json { render json: @tasks_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks_lists/1
  # PATCH/PUT /tasks_lists/1.json
  def update
    respond_to do |format|
      if @tasks_list.update(tasks_list_params)
        format.html { redirect_to @tasks_list, notice: 'Tasks list was successfully updated.' }
        format.json { render :show, status: :ok, location: @tasks_list }
      else
        format.html { render :edit }
        format.json { render json: @tasks_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks_lists/1
  # DELETE /tasks_lists/1.json
  def destroy
    @tasks_list.destroy
    respond_to do |format|
      format.html { redirect_to tasks_lists_url, notice: 'Tasks list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tasks_list
      @tasks_list = TasksList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tasks_list_params
      params.require(:tasks_list).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_lists_helper.rb
module TasksListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Otodo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks_lists/_form.html.erb
<%= form_for(@tasks_list) do |f| %>
  <% if @tasks_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tasks_list.errors.count, "error") %> prohibited this tasks_list from being saved:</h2>

      <ul>
      <% @tasks_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks_lists/edit.html.erb
<h1>Editing Tasks List</h1>

<%= render 'form' %>

<%= link_to 'Show', @tasks_list %> |
<%= link_to 'Back', tasks_lists_path %>

app/views/tasks_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tasks Lists</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks_lists.each do |tasks_list| %>
      <tr>
        <td><%= tasks_list.title %></td>
        <td><%= tasks_list.description %></td>
        <td><%= link_to 'Show', tasks_list %></td>
        <td><%= link_to 'Edit', edit_tasks_list_path(tasks_list) %></td>
        <td><%= link_to 'Destroy', tasks_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tasks list', new_tasks_list_path %>

app/views/tasks_lists/new.html.erb
<h1>New Tasks List</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_lists_path %>

app/views/tasks_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @tasks_list.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tasks_list.description %>
</p>

<%= link_to 'Edit', edit_tasks_list_path(@tasks_list) %> |
<%= link_to 'Back', tasks_lists_path %>